### ISSUE TITLE
Allow templates to be overridden

### ISSUE THREAD

**Issue by ramondelafuente** [systemli/ansible-role-jitsi-meet#9]
Looking into the different ansible roles for installing jitsi-meet, yours seems to be the best kept. But by having fixed templates in your role, some settings can't be changed (like enabling authentication) because the prosody.cfg.j2 file contains:

```
VirtualHost "{{ jitsi_meet_server_name }}"
	authentication = "anonymous"
```

Since this role contains many templates (because the jitsi-meet package installes multiple things together - maybe a few too many) it could be more flexible with regard to the template path.

In order to override templates, your role only needs to change the task with the template module:
```
- name: Copy additional prosody config
  template:
    src: prosody.cfg.j2

- name: Copy additional prosody config
  template:
    src: {{ some_template_path | default() }}prosody.cfg.j2
```

The `some_template_path` variable does not even have to exist, so it costs next to nothing, but it allows maximum flexibility downstream. It also saves you from having to keep up with every new release of jitsi-meet options as they come out (but are missing in your template).

I had to look it up myself, but [I wrote about this](https://future500.nl/articles/2015/04/12/being-a-star-in-galaxy/ ) a while back.

Do you think this is something you would incorporate?
